apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: kubernetes-cluster-himanshubungla
  labels:
    app: node-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: himanshusb12/app_himanshubungla:latest
        ports:
          - name: http
            containerPort: 7100
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: <SERVICE_NAME>
  namespace: kubernetes-cluster-himanshubungla
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      nodePort: <EXPOSED_PORT>
      port: 80
      targetPort: 7100
